#$ -S /bin/bash
#$ -cwd
#$ -q smp.q@@EPP
#$ -j y
#$ -o /mnt/lustre/scratch/epp/jp643/antinu/param_fitting/log.txt
##############################################

# Run with: qsub PDF_job.job

echo "Running param fitting job script"
module load sge
#module load gcc/5.4.0
# My rat source:
source /mnt/lustre/projects/epp/general/neutrino/jp643/rat_dependent/rat_source.sh
# RAT7 using ROOT5:
#source /research/epp/neutrino/snoplus/RAT7/env_rat-7.0.5.sh
# RAT7 using ROOT6
#source /research/epp/neutrino/snoplus/RAT7/install/env_rat-7.0.5.sh
cd /mnt/lustre/projects/epp/general/neutrino/jp643/rat_dependent/antinu/param_fitting/param_fitting/


# Run command
DATA_DIR="/mnt/lustre/scratch/epp/jp643/antinu/param_fitting/data/"
PDF_DIR="/mnt/lustre/scratch/epp/jp643/antinu/param_fitting/PDFs/"

./make_PDFs.exe ${DATA_DIR}1000_yr_full_scint_reactor.ntuple.root ${DATA_DIR}alpha_n_events.ntuple.root ${PDF_DIR}PDFs.root -9999

echo "Finished job!"
