#$ -S /bin/bash
#$ -cwd
#$ -q smp.q@@EPP
#$ -j y
#$ -o /mnt/lustre/scratch/epp/jp643/antinu/param_fitting/fitting_log.txt
##############################################

# Run with: qsub PDF_job.job

echo "Running param fitting job script"
module load sge
#module load gcc/5.4.0
# My rat source:
source /mnt/lustre/projects/epp/general/neutrino/jp643/rat_dependent/rat_source.sh
# RAT7 using ROOT5:
#source /research/epp/neutrino/snoplus/RAT7/env_rat-7.0.5.sh
# RAT7 using ROOT6
#source /research/epp/neutrino/snoplus/RAT7/install/env_rat-7.0.5.sh
cd /mnt/lustre/projects/epp/general/neutrino/jp643/rat_dependent/antinu/param_fitting/param_fitting/


# Run command
PDF_DIR="/mnt/lustre/scratch/epp/jp643/antinu/param_fitting/PDFs/"
FIT_DIR="/mnt/lustre/scratch/epp/jp643/antinu/param_fitting/likelihoods/"

./fit_params.exe ${PDF_DIR}PDFs.root ${FIT_DIR}min_ll.root

echo "Finished job!"
